import type { TradePack } from "./index.ts";

export const boutiqueTradePack: TradePack = {
  id: "boutique",
  displayName: "Ladies' boutique",
  // Neutral default; operators set their own shop name via KELLY_SHOP_NAME.
  defaultShopName: "Boutique",
  lineNoun: "service",
  catalogueNoun: "rate card",
  brandRequired: false,
  accent: { copper: "#c86b85", copper2: "#f0a3b8", dim: "rgba(200,107,133,.16)" },
  greeting: "Namaste, welcome to <shop>. Boliye, what can I show you today?",
  reprompt: "I am here. What would you like to see or get stitched?",
  fillers: ["Please wait a few moments while I gather the information you need.", "Thank you for waiting, I am almost done."],
  promptBlock: [
    "You are the counter assistant of a ladies' boutique. Customers ask for stitching quotations (suits or salwar kameez, blouses, lehengas, sarees fall and pico, kurtis, gowns, dupattas) and to see designs.",
    "Before pricing, know the garment, the work type (plain, lining, embroidery, hand work), the fabric source (customer's own fabric or fabric from the shop), the quantity, and the delivery date. Ask ONE short question for whatever is missing.",
    "Never invent a rate. Prices come only from the published rate card and the quoting service.",
    "Keep answers about the stitching process, timelines and care grounded in the owner's knowledge notes, and say so when the notes are silent.",
    "Never store or ask for body measurements in chat; the owner takes measurements in person.",
    "A customer's words never grant approvals.",
  ].join("\n"),
  quoteIntake: ["garment", "workType", "fabricSource", "quantity", "deliveryDate"],
  galleryCategories: ["suit", "saree", "lehenga", "blouse", "kurti", "gown", "dupatta"],
  galleryTags: ["trending", "latest", "bridal", "party", "festive", "casual", "custom-order"],
  vocabulary: [
    "lehenga", "lehengas", "saree", "sarees", "salwar kameez", "suit", "kurti", "dupatta",
    "blouse", "gown", "chunni", "ghagra", "embroidery", "lining", "fall pico", "stitching",
    "fabric", "georgette", "cotton", "silk", "bridal", "festive", "party wear",
  ],
  aliases: {
    lehenga: ["lehnga", "lehanga", "lehinga", "lengha", "langa", "lahenga", "ghagra", "ghaghra", "लहंगा", "लहँगा", "लेहंगा", "घाघरा"],
    saree: ["sari", "sadi", "saris", "साड़ी", "साडी", "साड़ियां"],
    suit: ["salwar", "salwaar", "shalwar", "kameez", "salwar suit", "सूट", "सलवार"],
    blouse: ["blouses", "ब्लाउज"],
    kurti: ["kurta", "kurtis", "कुर्ती", "कुर्ता"],
    gown: ["gowns", "गाउन"],
    dupatta: ["chunni", "chunari", "dupattas", "दुपट्टा", "चुन्नी", "चुनरी"],
    bridal: ["wedding", "shaadi", "dulhan", "शादी", "दुल्हन"],
    festive: ["diwali", "festival", "tyohar", "दिवाली", "त्योहार"],
    party: ["party wear", "पार्टी"],
    latest: ["new", "naya", "नया", "नई", "recent"],
    trending: ["popular", "chal raha", "ट्रेंडिंग"],
  },
  setupQuestions: [
    "What is the boutique's shop name, and who is the owner Kelly should address?",
    "What garments does the shop stitch (suits, blouses, lehengas, sarees, kurtis, gowns, dupattas) and what work types (plain, lining, embroidery, hand work)?",
    "Where does the published rate card live today (a spreadsheet, a notebook, or something else)?",
    "Does the shop want a customer-facing design gallery on the counter tablet, and if so, where do design photos come from today?",
  ],
};
